# frozen_string_literal: true

DiscourseBlog::Engine.routes.draw do
  get "/blog/publications/:topic_id/reviews" => "reviews#index"
  post "/blog/publications/:topic_id/reviews" => "reviews#create"
  delete "/blog/publications/:topic_id/reviews/:id" => "reviews#destroy"
  get "/blog/publications/:topic_id/reviews/:id/feedback" => "reviews#feedback"
  get "/blog/publications/:topic_id/feedback" => "reviews#topic_feedback"
  get "/blog/themes" => "themes#index"
  post "/blog/themes" => "themes#create"
  post "/blog/themes/import" => "themes#import"
  get "/blog/theme-authoring" => "themes#authoring"
  post "/blog/theme-authoring/preview" => "themes#working_preview"
  get "/blog/themes/:id" => "themes#show"
  put "/blog/themes/:id" => "themes#update"
  delete "/blog/themes/:id" => "themes#destroy"
  post "/blog/themes/:id/activate" => "themes#activate"
  post "/blog/themes/:id/pull" => "themes#pull"
  get "/blog/editor" => "editor#index"
  get "/blog/preview/:topic_id" => "editor#preview"
  get "/blog/publications/:topic_id" => "editor#show"
  get "/blog/publications/:topic_id/changes" => "editor#changes"
  put "/blog/publications/:topic_id" => "editor#update"
  post "/blog/publications/:topic_id/prepare" => "editor#prepare"
  post "/blog/publications/:topic_id/submit" => "editor#submit"
  post "/blog/publications/:topic_id/approve" => "editor#approve"
  post "/blog/publications/:topic_id/schedule" => "editor#schedule"
  delete "/blog/publications/:topic_id/schedule" => "editor#cancel_schedule"
  post "/blog/publications/:topic_id/publish" => "editor#publish"
  post "/blog/publications/:topic_id/return-to-drafts" => "editor#return_to_drafts"
  delete "/blog/publications/:topic_id" => "editor#destroy"
end
